; generated by PrusaSlicer 2.1.1+win64 on 2020-03-14 at 21:20:24 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R1
M73 Q0 S1
M201 X1000 Y1000 Z1000 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.8.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line
M73 Q5 S1
M73 P5 R1
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0
M221 S95
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K30 ; Filament gcode
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.1


G1 E-0.80000 F2100.00000
G1 Z0.600 F10800.000
;AFTER_LAYER_CHANGE
;0.1
G1 X102.694 Y84.121
G1 Z0.100
G1 E0.80000 F2100.00000
M204 S1000
G1 F6000
G1 X103.207 Y83.321 E0.01575
G1 X103.596 Y82.982 E0.00856
G1 X104.045 Y82.726 E0.00856
G1 X104.536 Y82.564 E0.00856
G1 X105.049 Y82.503 E0.00856
G1 X144.904 Y82.502 E0.66037
G1 X145.871 Y82.691 E0.01633
G1 X146.699 Y83.226 E0.01633
G1 X147.267 Y84.031 E0.01633
G1 X147.495 Y84.989 E0.01633
G1 X147.497 Y124.944 E0.66202
G1 X147.306 Y125.879 E0.01581
G1 X146.793 Y126.679 E0.01575
G1 X146.394 Y127.025 E0.00876
G1 X145.933 Y127.284 E0.00876
G1 X145.429 Y127.443 E0.00876
G1 X144.907 Y127.498 E0.00869
G1 X105.056 Y127.497 E0.66030
G1 X104.121 Y127.306 E0.01581
G1 X103.321 Y126.793 E0.01575
G1 X102.975 Y126.394 E0.00876
G1 X102.716 Y125.933 E0.00876
G1 X102.557 Y125.429 E0.00876
G1 X102.502 Y124.907 E0.00869
G1 X102.503 Y85.056 E0.66030
G1 X102.682 Y84.180 E0.01482
G1 F8640
G1 X103.207 Y83.321 E-0.23240
G1 X103.596 Y82.982 E-0.11933
G1 X104.045 Y82.726 E-0.11933
G1 X104.536 Y82.564 E-0.11933
G1 X105.049 Y82.503 E-0.11933
G1 X105.267 Y82.503 E-0.05028
G1 E-0.04000 F2100.00000
G1 Z0.700 F10800.000
G1 X104.214 Y83.087
G1 Z0.100
G1 E0.80000 F2100.00000
G1 F6000
G1 X105.064 Y82.901 E0.01441
G1 X144.904 Y82.901 E0.66012
G1 X145.726 Y83.062 E0.01388
G1 X146.428 Y83.518 E0.01388
G1 X146.908 Y84.204 E0.01388
G1 X147.098 Y85.020 E0.01388
G1 X147.099 Y124.933 E0.66134
G1 X146.937 Y125.729 E0.01346
G1 X146.497 Y126.412 E0.01346
G1 X145.773 Y126.919 E0.01465
G1 X144.903 Y127.099 E0.01471
G1 X105.067 Y127.099 E0.66006
G1 X104.271 Y126.937 E0.01346
G1 X103.588 Y126.497 E0.01346
G1 X103.081 Y125.773 E0.01465
G1 X102.901 Y124.903 E0.01471
G1 X102.901 Y85.067 E0.66006
G1 X103.063 Y84.271 E0.01346
G1 X103.503 Y83.588 E0.01346
G1 X104.165 Y83.122 E0.01342
G1 F8640
G1 X105.064 Y82.901 E-0.21369
G1 X107.430 Y82.901 E-0.54631
G1 E-0.04000 F2100.00000
G1 Z0.700 F10800.000
G1 X105.709 Y85.709
G1 Z0.100
G1 E0.80000 F2100.00000
G1 F6000
G1 X144.291 Y85.709 E0.63929
G1 X144.291 Y124.291 E0.63929
G1 X105.709 Y124.291 E0.63929
G1 X105.709 Y85.769 E0.63830
G1 X105.310 Y85.310 F10800.000
G1 F6000
G1 X144.690 Y85.310 E0.65250
G1 X144.690 Y124.690 E0.65250
G1 X105.310 Y124.690 E0.65250
G1 X105.310 Y85.370 E0.65151
G1 X105.696 Y85.414 F10800.000
G1 F8640
G1 X108.601 Y85.365 E-0.76000
G1 E-0.04000 F2100.00000
G1 Z0.700 F10800.000
G1 X106.635 Y124.172
G1 Z0.100
G1 E0.80000 F2100.00000
G1 F6000
G1 X106.007 Y123.544 E0.01473
G1 X106.007 Y122.980 E0.00937
G1 X107.020 Y123.993 E0.02377
G1 X107.585 Y123.993 E0.00937
G1 X106.007 Y122.415 E0.03701
G1 X106.007 Y121.851 E0.00937
G1 X108.149 Y123.993 E0.05026
G1 X108.714 Y123.993 E0.00937
G1 X106.007 Y121.286 E0.06351
G1 X106.007 Y120.722 E0.00937
G1 X109.278 Y123.993 E0.07675
G1 X109.842 Y123.993 E0.00937
G1 X106.007 Y120.158 E0.09000
G1 X106.007 Y119.593 E0.00937
G1 X110.407 Y123.993 E0.10325
G1 X110.971 Y123.993 E0.00937
G1 X106.007 Y119.029 E0.11649
G1 X106.007 Y118.464 E0.00937
G1 X111.536 Y123.993 E0.12974
G1 X112.100 Y123.993 E0.00937
G1 X106.007 Y117.900 E0.14299
G1 X106.007 Y117.335 E0.00937
G1 X112.665 Y123.993 E0.15623
G1 X113.229 Y123.993 E0.00937
G1 X106.007 Y116.771 E0.16948
G1 X106.007 Y116.206 E0.00937
G1 X113.794 Y123.993 E0.18273
G1 X114.358 Y123.993 E0.00937
G1 X106.007 Y115.642 E0.19597
G1 X106.007 Y115.077 E0.00937
G1 X114.923 Y123.993 E0.20922
G1 X115.487 Y123.993 E0.00937
G1 X106.007 Y114.513 E0.22247
G1 X106.007 Y113.948 E0.00937
G1 X116.052 Y123.993 E0.23571
G1 X116.616 Y123.993 E0.00937
G1 X106.007 Y113.384 E0.24896
G1 X106.007 Y112.819 E0.00937
G1 X117.181 Y123.993 E0.26221
G1 X117.745 Y123.993 E0.00937
G1 X106.007 Y112.255 E0.27545
G1 X106.007 Y111.691 E0.00937
G1 X118.309 Y123.993 E0.28870
G1 X118.874 Y123.993 E0.00937
G1 X106.007 Y111.126 E0.30195
G1 X106.007 Y110.562 E0.00937
G1 X119.438 Y123.993 E0.31519
G1 X120.003 Y123.993 E0.00937
G1 X106.007 Y109.997 E0.32844
G1 X106.007 Y109.433 E0.00937
G1 X120.567 Y123.993 E0.34169
G1 X121.132 Y123.993 E0.00937
G1 X106.007 Y108.868 E0.35493
G1 X106.007 Y108.304 E0.00937
G1 X121.696 Y123.993 E0.36818
G1 X122.261 Y123.993 E0.00937
G1 X106.007 Y107.739 E0.38143
G1 X106.007 Y107.175 E0.00937
G1 X122.825 Y123.993 E0.39467
G1 X123.390 Y123.993 E0.00937
G1 X106.007 Y106.610 E0.40792
G1 X106.007 Y106.046 E0.00937
G1 X123.954 Y123.993 E0.42117
G1 X124.519 Y123.993 E0.00937
G1 X106.007 Y105.481 E0.43441
G1 X106.007 Y104.917 E0.00937
G1 X125.083 Y123.993 E0.44766
G1 X125.647 Y123.993 E0.00937
G1 X106.007 Y104.353 E0.46091
G1 X106.007 Y103.788 E0.00937
G1 X126.212 Y123.993 E0.47415
G1 X126.776 Y123.993 E0.00937
G1 X106.007 Y103.224 E0.48740
G1 X106.007 Y102.659 E0.00937
G1 X127.341 Y123.993 E0.50065
G1 X127.905 Y123.993 E0.00937
G1 X106.007 Y102.095 E0.51389
G1 X106.007 Y101.530 E0.00937
G1 X128.470 Y123.993 E0.52714
G1 X129.034 Y123.993 E0.00937
G1 X106.007 Y100.966 E0.54039
G1 X106.007 Y100.401 E0.00937
G1 X129.599 Y123.993 E0.55363
G1 X130.163 Y123.993 E0.00937
G1 X106.007 Y99.837 E0.56688
G1 X106.007 Y99.272 E0.00937
G1 X130.728 Y123.993 E0.58013
G1 X131.292 Y123.993 E0.00937
G1 X106.007 Y98.708 E0.59337
G1 X106.007 Y98.143 E0.00937
G1 X131.857 Y123.993 E0.60662
G1 X132.421 Y123.993 E0.00937
G1 X106.007 Y97.579 E0.61987
G1 X106.007 Y97.014 E0.00937
G1 X132.986 Y123.993 E0.63311
G1 X133.550 Y123.993 E0.00937
G1 X106.007 Y96.450 E0.64636
G1 X106.007 Y95.886 E0.00937
G1 X134.114 Y123.993 E0.65961
G1 X134.679 Y123.993 E0.00937
G1 X106.007 Y95.321 E0.67285
G1 X106.007 Y94.757 E0.00937
G1 X135.243 Y123.993 E0.68610
G1 X135.808 Y123.993 E0.00937
G1 X106.007 Y94.192 E0.69935
G1 X106.007 Y93.628 E0.00937
G1 X136.372 Y123.993 E0.71259
G1 X136.937 Y123.993 E0.00937
G1 X106.007 Y93.063 E0.72584
G1 X106.007 Y92.499 E0.00937
G1 X137.501 Y123.993 E0.73909
G1 X138.066 Y123.993 E0.00937
G1 X106.007 Y91.934 E0.75234
G1 X106.007 Y91.370 E0.00937
G1 X138.630 Y123.993 E0.76558
G1 X139.195 Y123.993 E0.00937
G1 X106.007 Y90.805 E0.77883
G1 X106.007 Y90.241 E0.00937
G1 X139.759 Y123.993 E0.79208
G1 X140.324 Y123.993 E0.00937
G1 X106.007 Y89.676 E0.80532
G1 X106.007 Y89.112 E0.00937
G1 X140.888 Y123.993 E0.81857
G1 X141.452 Y123.993 E0.00937
G1 X106.007 Y88.548 E0.83182
G1 X106.007 Y87.983 E0.00937
G1 X142.017 Y123.993 E0.84506
G1 X142.581 Y123.993 E0.00937
G1 X106.007 Y87.419 E0.85831
G1 X106.007 Y86.854 E0.00937
G1 X143.146 Y123.993 E0.87156
G1 X143.710 Y123.993 E0.00937
G1 X106.007 Y86.290 E0.88480
G1 X106.007 Y86.007 E0.00468
G1 X106.290 Y86.007 E0.00468
G1 X143.993 Y123.710 E0.88480
G1 X143.993 Y123.146 E0.00937
G1 X106.854 Y86.007 E0.87156
G1 X107.419 Y86.007 E0.00937
G1 X143.993 Y122.581 E0.85831
G1 X143.993 Y122.017 E0.00937
G1 X107.983 Y86.007 E0.84506
G1 X108.548 Y86.007 E0.00937
G1 X143.993 Y121.452 E0.83181
G1 X143.993 Y120.888 E0.00937
G1 X109.112 Y86.007 E0.81857
G1 X109.676 Y86.007 E0.00937
G1 X143.993 Y120.324 E0.80532
G1 X143.993 Y119.759 E0.00937
G1 X110.241 Y86.007 E0.79207
G1 X110.805 Y86.007 E0.00937
G1 X143.993 Y119.195 E0.77883
G1 X143.993 Y118.630 E0.00937
G1 X111.370 Y86.007 E0.76558
G1 X111.934 Y86.007 E0.00937
G1 X143.993 Y118.066 E0.75233
G1 X143.993 Y117.501 E0.00937
G1 X112.499 Y86.007 E0.73909
G1 X113.063 Y86.007 E0.00937
G1 X143.993 Y116.937 E0.72584
G1 X143.993 Y116.372 E0.00937
G1 X113.628 Y86.007 E0.71259
G1 X114.192 Y86.007 E0.00937
G1 X143.993 Y115.808 E0.69935
G1 X143.993 Y115.243 E0.00937
G1 X114.757 Y86.007 E0.68610
G1 X115.321 Y86.007 E0.00937
G1 X143.993 Y114.679 E0.67285
G1 X143.993 Y114.114 E0.00937
G1 X115.886 Y86.007 E0.65961
G1 X116.450 Y86.007 E0.00937
G1 X143.993 Y113.550 E0.64636
G1 X143.993 Y112.986 E0.00937
G1 X117.014 Y86.007 E0.63311
G1 X117.579 Y86.007 E0.00937
G1 X143.993 Y112.421 E0.61987
G1 X143.993 Y111.857 E0.00937
G1 X118.143 Y86.007 E0.60662
G1 X118.708 Y86.007 E0.00937
G1 X143.993 Y111.292 E0.59337
G1 X143.993 Y110.728 E0.00937
G1 X119.272 Y86.007 E0.58013
G1 X119.837 Y86.007 E0.00937
G1 X143.993 Y110.163 E0.56688
G1 X143.993 Y109.599 E0.00937
G1 X120.401 Y86.007 E0.55363
G1 X120.966 Y86.007 E0.00937
G1 X143.993 Y109.034 E0.54039
G1 X143.993 Y108.470 E0.00937
G1 X121.530 Y86.007 E0.52714
G1 X122.095 Y86.007 E0.00937
G1 X143.993 Y107.905 E0.51389
G1 X143.993 Y107.341 E0.00937
G1 X122.659 Y86.007 E0.50065
G1 X123.224 Y86.007 E0.00937
G1 X143.993 Y106.776 E0.48740
G1 X143.993 Y106.212 E0.00937
G1 X123.788 Y86.007 E0.47415
G1 X124.353 Y86.007 E0.00937
G1 X143.993 Y105.647 E0.46091
G1 X143.993 Y105.083 E0.00937
G1 X124.917 Y86.007 E0.44766
G1 X125.481 Y86.007 E0.00937
G1 X143.993 Y104.519 E0.43441
G1 X143.993 Y103.954 E0.00937
G1 X126.046 Y86.007 E0.42117
G1 X126.610 Y86.007 E0.00937
G1 X143.993 Y103.390 E0.40792
G1 X143.993 Y102.825 E0.00937
G1 X127.175 Y86.007 E0.39467
G1 X127.739 Y86.007 E0.00937
G1 X143.993 Y102.261 E0.38143
G1 X143.993 Y101.696 E0.00937
G1 X128.304 Y86.007 E0.36818
G1 X128.868 Y86.007 E0.00937
G1 X143.993 Y101.132 E0.35493
G1 X143.993 Y100.567 E0.00937
G1 X129.433 Y86.007 E0.34169
G1 X129.997 Y86.007 E0.00937
G1 X143.993 Y100.003 E0.32844
G1 X143.993 Y99.438 E0.00937
G1 X130.562 Y86.007 E0.31519
G1 X131.126 Y86.007 E0.00937
G1 X143.993 Y98.874 E0.30195
G1 X143.993 Y98.309 E0.00937
G1 X131.691 Y86.007 E0.28870
M73 Q85 S0
G1 X132.255 Y86.007 E0.00937
G1 X143.993 Y97.745 E0.27545
M73 P86 R0
G1 X143.993 Y97.180 E0.00937
G1 X132.820 Y86.007 E0.26221
G1 X133.384 Y86.007 E0.00937
G1 X143.993 Y96.616 E0.24896
G1 X143.993 Y96.052 E0.00937
G1 X133.948 Y86.007 E0.23571
G1 X134.513 Y86.007 E0.00937
G1 X143.993 Y95.487 E0.22247
G1 X143.993 Y94.923 E0.00937
G1 X135.077 Y86.007 E0.20922
G1 X135.642 Y86.007 E0.00937
G1 X143.993 Y94.358 E0.19597
G1 X143.993 Y93.794 E0.00937
G1 X136.206 Y86.007 E0.18273
G1 X136.771 Y86.007 E0.00937
G1 X143.993 Y93.229 E0.16948
G1 X143.993 Y92.665 E0.00937
G1 X137.335 Y86.007 E0.15623
G1 X137.900 Y86.007 E0.00937
G1 X143.993 Y92.100 E0.14299
G1 X143.993 Y91.536 E0.00937
G1 X138.464 Y86.007 E0.12974
G1 X139.029 Y86.007 E0.00937
G1 X143.993 Y90.971 E0.11649
G1 X143.993 Y90.407 E0.00937
G1 X139.593 Y86.007 E0.10325
G1 X140.158 Y86.007 E0.00937
G1 X143.993 Y89.842 E0.09000
G1 X143.993 Y89.278 E0.00937
G1 X140.722 Y86.007 E0.07675
G1 X141.286 Y86.007 E0.00937
G1 X143.993 Y88.714 E0.06351
G1 X143.993 Y88.149 E0.00937
G1 X141.851 Y86.007 E0.05026
G1 X142.415 Y86.007 E0.00937
G1 X143.993 Y87.585 E0.03701
G1 X143.993 Y87.020 E0.00937
G1 X142.980 Y86.007 E0.02377
G1 X143.544 Y86.007 E0.00937
G1 X144.172 Y86.635 E0.01473
G1 F8640;_WIPE
G1 X143.544 Y86.007 E-0.20493
G1 F8640;_WIPE
G1 X142.980 Y86.007 E-0.13034
G1 F8640;_WIPE
G1 X143.993 Y87.020 E-0.33069
G1 F8640;_WIPE
G1 X143.993 Y87.427 E-0.09404
G1 E-0.04000 F2100.00000
G1 Z0.700 F10800.000
; Filament-specific end gcode
G4 ; wait
M221 S100
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z30.7 ; Move print head up
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 72.2
; filament used [cm3] = 0.2
; filament used [g] = 0.2
; filament cost = 0.0
; total filament used [g] = 0.2
; total filament cost = 0.0
; estimated printing time (normal mode) = 1m 13s
; estimated printing time (silent mode) = 1m 14s

; avoid_crossing_perimeters = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 2
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.7
; bridge_speed = 180
; brim_width = 0
; clip_multipart_objects = 1
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4 and ! single_extruder_multi_material";"! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; duplicate_distance = 6
; elefant_foot_compensation = 0.1
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 180
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 25
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 24.99
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Prusament PLA"
; filament_soluble = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; fill_angle = 45
; fill_density = 15%
; fill_pattern = rectilinear
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.1
; first_layer_speed = 100
; first_layer_temperature = 215
; gap_fill_speed = 180
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 180
; inherits_cummulative = "0.10mm DETAIL MK3";;
; interface_shells = 0
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.1
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 1000,1000
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 180
; perimeters = 2
; post_process = 
; print_host = 
; print_settings_id = 0.10mm Fast
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; printhost_apikey = 
; printhost_cafile = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.6
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = nearest
; serial_port = 
; serial_speed = 250000
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 1
; skirts = 1
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 180
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{elsif nozzle_diameter[0]==0.6}18{else}30{endif} ; Filament gcode"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.8.1 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0 F1000.0 ; intro line\nG1 X100.0 E12.5 F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height<0.075}100{else}95{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 180
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 215
; thin_walls = 0
; threads = 8
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = rectilinear
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 180
; top_solid_layers = 3
; travel_speed = 180
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
